### ISSUE TITLE
pip error: No such file or directory: '/tmp/pip-...-build/setup.py'

### ISSUE THREAD

**Issue by akshetty9** [gitaroktato/cassandra-replication-latency-tools#1]
> Downloading/unpacking git+git://github.com/gitaroktato/cassandra-replication-latency-tools.git
>   Cloning git://github.com/gitaroktato/cassandra-replication-latency-tools.git to /tmp/pip-asEndE-build
>   Running setup.py (path:/tmp/pip-asEndE-build/setup.py) egg_info for package from git+git://github.com/gitaroktato/cassandra-replication-latency-tools.git
>     Traceback (most recent call last):
>       File "<string>", line 17, in <module>
>     IOError: [Errno 2] No such file or directory: '/tmp/pip-asEndE-build/setup.py'
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
> 
>   File "<string>", line 17, in <module>
> 
> IOError: [Errno 2] No such file or directory: '/tmp/pip-asEndE-build/setup.py'
> 
> ----------------------------------------
> Cleaning up...
> Command python setup.py egg_info failed with error code 1 in /tmp/pip-asEndE-build
> Storing debug log for failure in /home/ubuntu/.pip/pip.log

Does it require a setup.py file?

**Comment by gitaroktato** [comment]
@akshetty9 Thanks for visiting this repo. Unfortunately there's no pip support at the moment. Please check README.md for details and howtos.

**Comment by akshetty9** [comment]
thanks
